### ISSUE TITLE
Problems starting an imported privkeys wallet from python code

### ISSUE THREAD

**Issue by XaviP** [faircoin/electrumfair#8]
We are starting electrumfair wallet from python code like this:
```
import electrumfair
c = electrumfair.SimpleConfig()
network = electrumfair.Network(c)
network.start()
storage = electrumfair.WalletStorage(wallet_path)
wallet = electrumfair.Wallet(storage)
wallet.start_threads(network)
```
This is currently working ok with wallet updated from seed, but we are facing problems with an imported privkeys wallet. From gui, the wallet seems ok (all addresses recognized), but when starting the wallet from python code, only 20 addresses from a seed are recognized, no one of the addresses from the imported private keys.

Edit: from console the imported privkeys addresses doesn't appear neither with `electrumfair listaddresses`

**Comment by santiky** [comment]
the "import private keys" is not a way to go due to we need to sweep the funds, and is required we need use the same wallet with the same balance and addresses for user.

I have the wallet updated to 2.7.18 and striped the false addresses created but i was facing another problem creating transactions, i thought related to 
https://github.com/spesmilo/electrum/issues/2242

I updated to 2.8.3 (branch 2.8.3-fc, ready to test and use, works for me in debian stretch) but it does not solved the error. 
Perhaps is related to 
https://github.com/spesmilo/electrum/issues/2509
fixed in 
https://github.com/spesmilo/electrum/commit/7ea2cb41e88ba2ef9f1bacc2059b637b9702e192
so i am updating to electrum master but some classes were some refactored (blockchain.py) and it is giving problems to run (changes in the serialized header function and so).

**Comment by thokon00** [comment]
Is this issue still relevant?

**Comment by santiky** [comment]
Not really, can be closed
